//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_PRODUCTOS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Producto
    {
        [Display(Name = "ID")]
        public int ProductoID { get; set; }
        [Display(Name ="Producto")]
        public string Nombre { get; set; }
        [Display(Name = "Precio")]
        public decimal Precio { get; set; }
        [Display(Name = "Stock")]
        public int Stock { get; set; }
        [Display(Name = "Categoria")]
        public Nullable<int> CategoriaID { get; set; }
        [Display(Name = "Categoria")]
        public virtual Categoria Categoria { get; set; }
    }
}
